/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as NotAdminRouteImport } from './routes/not-admin'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppEmailVerifiedRouteImport } from './routes/_app/email-verified'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as PublicCoursesIndexRouteImport } from './routes/_public/courses/index'
import { Route as PublicCoursesSlugRouteImport } from './routes/_public/courses/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAdminCoursesIndexRouteImport } from './routes/_app/admin/courses/index'
import { Route as ApiS3UploadIndexRouteImport } from './routes/api/s3/upload/index'
import { Route as AppAdminCoursesCourseIdIndexRouteImport } from './routes/_app/admin/courses/$courseId/index'
import { Route as AppAdminCoursesCreateIndexRouteImport } from './routes/_app/admin/courses/create/index'
import { Route as AppAdminCoursesCourseIdDeleteIndexRouteImport } from './routes/_app/admin/courses/$courseId/delete/index'
import { Route as AppAdminCoursesCourseIdEditIndexRouteImport } from './routes/_app/admin/courses/$courseId/edit/index'
import { Route as AppAdminCoursesCourseIdChapterIdLessonIdIndexRouteImport } from './routes/_app/admin/courses/$courseId/$chapterId/$lessonId/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const NotAdminRoute = NotAdminRouteImport.update({
  id: '/not-admin',
  path: '/not-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmailVerifiedRoute = AppEmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const PublicCoursesIndexRoute = PublicCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCoursesSlugRoute = PublicCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminCoursesIndexRoute = AppAdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const ApiS3UploadIndexRoute = ApiS3UploadIndexRouteImport.update({
  id: '/api/s3/upload/',
  path: '/api/s3/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminCoursesCourseIdIndexRoute =
  AppAdminCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminCoursesCreateIndexRoute =
  AppAdminCoursesCreateIndexRouteImport.update({
    id: '/courses/create/',
    path: '/courses/create/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminCoursesCourseIdDeleteIndexRoute =
  AppAdminCoursesCourseIdDeleteIndexRouteImport.update({
    id: '/courses/$courseId/delete/',
    path: '/courses/$courseId/delete/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminCoursesCourseIdEditIndexRoute =
  AppAdminCoursesCourseIdEditIndexRouteImport.update({
    id: '/courses/$courseId/edit/',
    path: '/courses/$courseId/edit/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminCoursesCourseIdChapterIdLessonIdIndexRoute =
  AppAdminCoursesCourseIdChapterIdLessonIdIndexRouteImport.update({
    id: '/courses/$courseId/$chapterId/$lessonId/',
    path: '/courses/$courseId/$chapterId/$lessonId/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/not-admin': typeof NotAdminRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/email-verified': typeof AppEmailVerifiedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/courses/$slug': typeof PublicCoursesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/courses/': typeof PublicCoursesIndexRoute
  '/admin/courses/': typeof AppAdminCoursesIndexRoute
  '/api/s3/upload/': typeof ApiS3UploadIndexRoute
  '/admin/courses/$courseId/': typeof AppAdminCoursesCourseIdIndexRoute
  '/admin/courses/create/': typeof AppAdminCoursesCreateIndexRoute
  '/admin/courses/$courseId/delete/': typeof AppAdminCoursesCourseIdDeleteIndexRoute
  '/admin/courses/$courseId/edit/': typeof AppAdminCoursesCourseIdEditIndexRoute
  '/admin/courses/$courseId/$chapterId/$lessonId/': typeof AppAdminCoursesCourseIdChapterIdLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/not-admin': typeof NotAdminRoute
  '/verify-email': typeof VerifyEmailRoute
  '/email-verified': typeof AppEmailVerifiedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/courses/$slug': typeof PublicCoursesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/courses': typeof PublicCoursesIndexRoute
  '/admin/courses': typeof AppAdminCoursesIndexRoute
  '/api/s3/upload': typeof ApiS3UploadIndexRoute
  '/admin/courses/$courseId': typeof AppAdminCoursesCourseIdIndexRoute
  '/admin/courses/create': typeof AppAdminCoursesCreateIndexRoute
  '/admin/courses/$courseId/delete': typeof AppAdminCoursesCourseIdDeleteIndexRoute
  '/admin/courses/$courseId/edit': typeof AppAdminCoursesCourseIdEditIndexRoute
  '/admin/courses/$courseId/$chapterId/$lessonId': typeof AppAdminCoursesCourseIdChapterIdLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/not-admin': typeof NotAdminRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/email-verified': typeof AppEmailVerifiedRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/courses/$slug': typeof PublicCoursesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_public/courses/': typeof PublicCoursesIndexRoute
  '/_app/admin/courses/': typeof AppAdminCoursesIndexRoute
  '/api/s3/upload/': typeof ApiS3UploadIndexRoute
  '/_app/admin/courses/$courseId/': typeof AppAdminCoursesCourseIdIndexRoute
  '/_app/admin/courses/create/': typeof AppAdminCoursesCreateIndexRoute
  '/_app/admin/courses/$courseId/delete/': typeof AppAdminCoursesCourseIdDeleteIndexRoute
  '/_app/admin/courses/$courseId/edit/': typeof AppAdminCoursesCourseIdEditIndexRoute
  '/_app/admin/courses/$courseId/$chapterId/$lessonId/': typeof AppAdminCoursesCourseIdChapterIdLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-admin'
    | '/verify-email'
    | '/admin'
    | '/email-verified'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/courses/$slug'
    | '/api/auth/$'
    | '/admin/'
    | '/courses/'
    | '/admin/courses/'
    | '/api/s3/upload/'
    | '/admin/courses/$courseId/'
    | '/admin/courses/create/'
    | '/admin/courses/$courseId/delete/'
    | '/admin/courses/$courseId/edit/'
    | '/admin/courses/$courseId/$chapterId/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-admin'
    | '/verify-email'
    | '/email-verified'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/courses/$slug'
    | '/api/auth/$'
    | '/admin'
    | '/courses'
    | '/admin/courses'
    | '/api/s3/upload'
    | '/admin/courses/$courseId'
    | '/admin/courses/create'
    | '/admin/courses/$courseId/delete'
    | '/admin/courses/$courseId/edit'
    | '/admin/courses/$courseId/$chapterId/$lessonId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_public'
    | '/not-admin'
    | '/verify-email'
    | '/_app/admin'
    | '/_app/email-verified'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_public/'
    | '/_public/courses/$slug'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_public/courses/'
    | '/_app/admin/courses/'
    | '/api/s3/upload/'
    | '/_app/admin/courses/$courseId/'
    | '/_app/admin/courses/create/'
    | '/_app/admin/courses/$courseId/delete/'
    | '/_app/admin/courses/$courseId/edit/'
    | '/_app/admin/courses/$courseId/$chapterId/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  NotAdminRoute: typeof NotAdminRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiS3UploadIndexRoute: typeof ApiS3UploadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-admin': {
      id: '/not-admin'
      path: '/not-admin'
      fullPath: '/not-admin'
      preLoaderRoute: typeof NotAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/email-verified': {
      id: '/_app/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof AppEmailVerifiedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_public/courses/': {
      id: '/_public/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof PublicCoursesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/courses/$slug': {
      id: '/_public/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof PublicCoursesSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/courses/': {
      id: '/_app/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AppAdminCoursesIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/api/s3/upload/': {
      id: '/api/s3/upload/'
      path: '/api/s3/upload'
      fullPath: '/api/s3/upload/'
      preLoaderRoute: typeof ApiS3UploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/courses/$courseId/': {
      id: '/_app/admin/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId/'
      preLoaderRoute: typeof AppAdminCoursesCourseIdIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/courses/create/': {
      id: '/_app/admin/courses/create/'
      path: '/courses/create'
      fullPath: '/admin/courses/create/'
      preLoaderRoute: typeof AppAdminCoursesCreateIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/courses/$courseId/delete/': {
      id: '/_app/admin/courses/$courseId/delete/'
      path: '/courses/$courseId/delete'
      fullPath: '/admin/courses/$courseId/delete/'
      preLoaderRoute: typeof AppAdminCoursesCourseIdDeleteIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/courses/$courseId/edit/': {
      id: '/_app/admin/courses/$courseId/edit/'
      path: '/courses/$courseId/edit'
      fullPath: '/admin/courses/$courseId/edit/'
      preLoaderRoute: typeof AppAdminCoursesCourseIdEditIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/courses/$courseId/$chapterId/$lessonId/': {
      id: '/_app/admin/courses/$courseId/$chapterId/$lessonId/'
      path: '/courses/$courseId/$chapterId/$lessonId'
      fullPath: '/admin/courses/$courseId/$chapterId/$lessonId/'
      preLoaderRoute: typeof AppAdminCoursesCourseIdChapterIdLessonIdIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminCoursesIndexRoute: typeof AppAdminCoursesIndexRoute
  AppAdminCoursesCourseIdIndexRoute: typeof AppAdminCoursesCourseIdIndexRoute
  AppAdminCoursesCreateIndexRoute: typeof AppAdminCoursesCreateIndexRoute
  AppAdminCoursesCourseIdDeleteIndexRoute: typeof AppAdminCoursesCourseIdDeleteIndexRoute
  AppAdminCoursesCourseIdEditIndexRoute: typeof AppAdminCoursesCourseIdEditIndexRoute
  AppAdminCoursesCourseIdChapterIdLessonIdIndexRoute: typeof AppAdminCoursesCourseIdChapterIdLessonIdIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminCoursesIndexRoute: AppAdminCoursesIndexRoute,
  AppAdminCoursesCourseIdIndexRoute: AppAdminCoursesCourseIdIndexRoute,
  AppAdminCoursesCreateIndexRoute: AppAdminCoursesCreateIndexRoute,
  AppAdminCoursesCourseIdDeleteIndexRoute:
    AppAdminCoursesCourseIdDeleteIndexRoute,
  AppAdminCoursesCourseIdEditIndexRoute: AppAdminCoursesCourseIdEditIndexRoute,
  AppAdminCoursesCourseIdChapterIdLessonIdIndexRoute:
    AppAdminCoursesCourseIdChapterIdLessonIdIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppEmailVerifiedRoute: typeof AppEmailVerifiedRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppEmailVerifiedRoute: AppEmailVerifiedRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCoursesSlugRoute: typeof PublicCoursesSlugRoute
  PublicCoursesIndexRoute: typeof PublicCoursesIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicCoursesSlugRoute: PublicCoursesSlugRoute,
  PublicCoursesIndexRoute: PublicCoursesIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  NotAdminRoute: NotAdminRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiS3UploadIndexRoute: ApiS3UploadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
